/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jyqqhw_jnidemo_JniUtil */

#ifndef _Included_com_jyqqhw_jnidemo_JniUtil
#define _Included_com_jyqqhw_jnidemo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jyqqhw_jnidemo_JniUtil
 * Method:    printJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jyqqhw_jnidemo_JniUtil_printJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
